# Lab | Data Aggregation and Filtering

In this challenge, we will continue to work with customer data from an insurance company. We will use the dataset called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by first performing data cleaning, formatting, and structuring.

1. Create a new DataFrame that only includes customers who:
   - have a **low total_claim_amount** (e.g., below $1,000),
   - have a response "Yes" to the last marketing campaign.

In [2]:
import pandas as pd
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv"
df = pd.read_csv(url)
df.head()

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2/18/11,Employed,M,...,0.0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1,KX64629,California,2228.525238,No,Basic,College,1/18/11,Unemployed,F,...,0.0,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,...,0.0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,1/17/11,Medical Leave,F,...,NaN,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN

In [4]:
df.columns

Index(['Unnamed: 0', 'Customer', 'State', 'Customer Lifetime Value',
       'Response', 'Coverage', 'Education', 'Effective To Date',
       'EmploymentStatus', 'Gender', 'Income', 'Location Code',
       'Marital Status', 'Monthly Premium Auto', 'Months Since Last Claim',
       'Months Since Policy Inception', 'Number of Open Complaints',
       'Number of Policies', 'Policy Type', 'Policy', 'Renew Offer Type',
       'Sales Channel', 'Total Claim Amount', 'Vehicle Class', 'Vehicle Size',
       'Vehicle Type'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     10910 non-null  int64
 1   Customer                       10910 non-null  object
 2   State                          10279 non-null  object
 3   Customer Lifetime Value        10910 non-null  float64
 4   Response                       10279 non-null  object
 5   Coverage                       10910 non-null  object
 6   Education                      10910 non-null  object
 7   Effective To Date              10910 non-null  object
 8   EmploymentStatus               10910 non-null  object
 9   Gender                         10910 non-null  object
 10  Income                         10910 non-null  int64
 11  Location Code                  10910 non-null  object
 12  Marital Status                 10910 non-null  object
 13  Monthly Premium Auto           10910 non-null  int64
 14  Months Since Last Claim        10277 non-null  float64
 15  Months Since Policy Inception  10910 non-null  int64
 16  Number of Open Complaints      10277 non-null  float64
 17  Number of Policies             10910 non-null  int64
 18  Policy Type                    10910 non-null  object
 19  Policy                         10910 non-null  object
 20  Renew Offer Type               10910 non-null  object
 21  Sales Channel                  10910 non-null  object
 22  Total Claim Amount             10910 non-null  float64
 23  Vehicle Class                  10288 non-null  object
 24  Vehicle Size                   10288 non-null  object
 25  Vehicle Type                   5428 non-null   object
dtypes: float64(4), int64(5), object(17)
memory usage: 2.2+ MB

In [6]:
df.isna().sum()

Unnamed: 0                          0
Customer                            0
State                             631
Customer Lifetime Value             0
Response                          631
Coverage                            0
Education                           0
Effective To Date                   0
EmploymentStatus                    0
Gender                              0
Income                              0
Location Code                       0
Marital Status                      0
Monthly Premium Auto                0
Months Since Last Claim           633
Months Since Policy Inception       0
Number of Open Complaints         633
Number of Policies                  0
Policy Type                         0
Policy                              0
Renew Offer Type                    0
Sales Channel                       0
Total Claim Amount                  0
Vehicle Class                     622
Vehicle Size                      622
Vehicle Type                     5482
dtype: int64

In [8]:
df = df.drop(columns = ["Unnamed: 0"], errors="ignore")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 25 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Customer                       10910 non-null  object
 1   State                          10279 non-null  object
 2   Customer Lifetime Value        10910 non-null  float64
 3   Response                       10279 non-null  object
 4   Coverage                       10910 non-null  object
 5   Education                      10910 non-null  object
 6   Effective To Date              10910 non-null  object
 7   EmploymentStatus               10910 non-null  object
 8   Gender                         10910 non-null  object
 9   Income                         10910 non-null  int64
 10  Location Code                  10910 non-null  object
 11  Marital Status                 10910 non-null  object
 12  Monthly Premium Auto           10910 non-null  int64
 13  Months Since Last Claim        10277 non-null  float64
 14  Months Since Policy Inception  10910 non-null  int64
 15  Number of Open Complaints      10277 non-null  float64
 16  Number of Policies             10910 non-null  int64
 17  Policy Type                    10910 non-null  object
 18  Policy                         10910 non-null  object
 19  Renew Offer Type               10910 non-null  object
 20  Sales Channel                  10910 non-null  object
 21  Total Claim Amount             10910 non-null  float64
 22  Vehicle Class                  10288 non-null  object
 23  Vehicle Size                   10288 non-null  object
 24  Vehicle Type                   5428 non-null   object
dtypes: float64(4), int64(4), object(17)
memory usage: 2.1+ MB

In [9]:
#Standardize column names

df.columns = df.columns.str.lower().str.replace(" ","_")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 25 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   customer                       10910 non-null  object
 1   state                          10279 non-null  object
 2   customer_lifetime_value        10910 non-null  float64
 3   response                       10279 non-null  object
 4   coverage                       10910 non-null  object
 5   education                      10910 non-null  object
 6   effective_to_date              10910 non-null  object
 7   employmentstatus               10910 non-null  object
 8   gender                         10910 non-null  object
 9   income                         10910 non-null  int64
 10  location_code                  10910 non-null  object
 11  marital_status                 10910 non-null  object
 12  monthly_premium_auto           10910 non-null  int64
 13  months_since_last_claim        10277 non-null  float64
 14  months_since_policy_inception  10910 non-null  int64
 15  number_of_open_complaints      10277 non-null  float64
 16  number_of_policies             10910 non-null  int64
 17  policy_type                    10910 non-null  object
 18  policy                         10910 non-null  object
 19  renew_offer_type               10910 non-null  object
 20  sales_channel                  10910 non-null  object
 21  total_claim_amount             10910 non-null  float64
 22  vehicle_class                  10288 non-null  object
 23  vehicle_size                   10288 non-null  object
 24  vehicle_type                   5428 non-null   object
dtypes: float64(4), int64(4), object(17)
memory usage: 2.1+ MB

In [14]:
#Clean empty rows

df = df.dropna(how="all")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 25 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   customer                       10910 non-null  object
 1   state                          10279 non-null  object
 2   customer_lifetime_value        10910 non-null  float64
 3   response                       10279 non-null  object
 4   coverage                       10910 non-null  object
 5   education                      10910 non-null  object
 6   effective_to_date              10910 non-null  object
 7   employmentstatus               10910 non-null  object
 8   gender                         10910 non-null  object
 9   income                         10910 non-null  int64
 10  location_code                  10910 non-null  object
 11  marital_status                 10910 non-null  object
 12  monthly_premium_auto           10910 non-null  int64
 13  months_since_last_claim        10277 non-null  float64
 14  months_since_policy_inception  10910 non-null  int64
 15  number_of_open_complaints      10277 non-null  float64
 16  number_of_policies             10910 non-null  int64
 17  policy_type                    10910 non-null  object
 18  policy                         10910 non-null  object
 19  renew_offer_type               10910 non-null  object
 20  sales_channel                  10910 non-null  object
 21  total_claim_amount             10910 non-null  float64
 22  vehicle_class                  10288 non-null  object
 23  vehicle_size                   10288 non-null  object
 24  vehicle_type                   5428 non-null   object
dtypes: float64(4), int64(4), object(17)
memory usage: 2.1+ MB

In [16]:
df['response'].unique()

array(['No', 'Yes', nan], dtype=object)

In [19]:
'''
New DataFrame that only includes customers who:
have a low total_claim_amount (e.g., below $1,000),
have a response "Yes" to the last marketing campaign.
'''

filtered_df = df [
    (df["total_claim_amount"] < 1000)&
    (df["response"]=="Yes")
    ]

filtered_df.head()

,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,income,...,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,49078,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
8,FM55990,California,5989.773931,Yes,Premium,College,1/19/11,Employed,M,66839,...,0.0,1,Personal Auto,Personal L1,Offer2,Branch,739.200000,Sports Car,Medsize,NaN
15,CW49887,California,4626.801093,Yes,Basic,Master,1/16/11,Employed,F,79487,...,0.0,1,Special Auto,Special L1,Offer2,Branch,547.200000,SUV,Medsize,NaN
19,NJ54277,California,3746.751625,Yes,Extended,College,2/26/11,Employed,F,41479,...,1.0,1,Personal Auto,Personal L2,Offer2,Call Center,19.575683,Two-Door Car,Large,A
27,MQ68407,Oregon,4376.363592,Yes,Premium,Bachelor,2/28/11,Employed,F,63774,...,0.0,1,Personal Auto,Personal L3,Offer2,Agent,60.036683,Four-Door Car,Medsize,NaN

In [21]:
filtered_df.shape

(1399, 25)

2. Using the original Dataframe, analyze:
   - the average `monthly_premium` and/or customer lifetime value by `policy_type` and `gender` for customers who responded "Yes", and
   - compare these insights to `total_claim_amount` patterns, and discuss which segments appear most profitable or low-risk for the company.

In [23]:
#Customer that responded "Yes"
yes_df = df[df["response"]=="Yes"]

In [30]:
#Average monthly_premium vs customer lifetime value vs total_claim_amount
premium_summary= (
    yes_df.groupby(["policy_type","gender"])
    .agg({
        "monthly_premium_auto":"mean",
        "customer_lifetime_value":"mean",
        "total_claim_amount":"mean"
    })
    
    .round(2)
    .reset_index()
)
premium_summary

,policy_type,gender,monthly_premium_auto,customer_lifetime_value,total_claim_amount
0,Corporate Auto,F,94.30,7712.63,433.74
1,Corporate Auto,M,92.19,7944.47,408.58
2,Personal Auto,F,99.00,8339.79,452.97
3,Personal Auto,M,91.09,7448.38,457.01
4,Special Auto,F,92.31,7691.58,453.28
5,Special Auto,M,86.34,8247.09,429.53

In [ ]:
'''The most profitable segment -> Female Personal Auto with highest monthly premium and highest clv.
Second best -> Male Special Auto with high clv and second lower claim amount.

Males with Corporate Auto are more stable with less claim ampunts of all.

'''

3. Analyze the total number of customers who have policies in each state, and then filter the results to only include states where there are more than 500 customers.

In [35]:
'''No. customers - policies - each state (>500 customers)'''
state_customers = df.groupby("state")["customer"].count().reset_index()
state_customers = state_customers .rename(columns={"customer":"total_customers"})
state_customers

        state  total_customers
0     Arizona             1937
1  California             3552
2      Nevada              993
3      Oregon             2909
4  Washington              888

In [38]:
#filter more than 500
state_customers_500 = state_customers[state_customers["total_customers"]>500]
state_customers_500

        state  total_customers
0     Arizona             1937
1  California             3552
2      Nevada              993
3      Oregon             2909
4  Washington              888

In [39]:
#Sort
state_customers_500 = state_customers_500.sort_values(
    by = "total_customers",
    ascending = False
)
state_customers_500

        state  total_customers
1  California             3552
3      Oregon             2909
0     Arizona             1937
2      Nevada              993
4  Washington              888

In [ ]:
'''
California has the most customers, having the highest amount of customer distribution there.

Washington and Nevada can be an opportunity to increase the market.
'''

4. Find the maximum, minimum, and median customer lifetime value by education level and gender. Write your conclusions.

In [40]:
clv_statistics = (
    df.groupby(["education","gender"])["customer_lifetime_value"]
    .agg(["max","min","median"])
    .round(2)
    .reset_index()
)

clv_statistics

              education gender       max      min   median
0              Bachelor      F  73225.96  1904.00  5640.51
1              Bachelor      M  67907.27  1898.01  5548.03
2               College      F  61850.19  1898.68  5623.61
3               College      M  61134.68  1918.12  6005.85
4                Doctor      F  44856.11  2395.57  5332.46
5                Doctor      M  32677.34  2267.60  5577.67
6  High School or Below      F  55277.45  2144.92  6039.55
7  High School or Below      M  83325.38  1940.98  6286.73
8                Master      F  51016.07  2417.78  5729.86
9                Master      M  50568.26  2272.31  5579.10

In [ ]:
'''
Educational level seems to have more impact on customer lifetime value than gender.

There are significant outliers in some segments(ex. Bachelor F, High School or Below M), 
indicating the presence of a few very high-value customers.

Customers with 'High School or Below' and 'College' education levels 
have the highest median CLV, indicating they are more valuable on average.

Customers with a Doctor degree show lower median values.

'''

## Bonus

5. The marketing team wants to analyze the number of policies sold by state and month. Present the data in a table where the months are arranged as columns and the states are arranged as rows.

In [45]:
df["effective_to_date"]=pd.to_datetime(df["effective_to_date"])
df["month"]=df["effective_to_date"].dt.month
df.head()

,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,income,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,48029,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN,2
1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,0,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN,1
2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,22139,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A,2
3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,49078,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,1
4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,23675,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN,1

In [44]:
#Policies (customer) - state/month
policies_mkt = pd.pivot_table(
    df,
    values="customer",
    index= "state",
    columns= "month",
    aggfunc= "count"
)

policies_mkt

month          1     2
state
Arizona     1008   929
California  1918  1634
Nevada       551   442
Oregon      1565  1344
Washington   463   425

6.  Display a new DataFrame that contains the number of policies sold by month, by state, for the top 3 states with the highest number of policies sold.

*Hint:*
- *To accomplish this, you will first need to group the data by state and month, then count the number of policies sold for each group. Afterwards, you will need to sort the data by the count of policies sold in descending order.*
- *Next, you will select the top 3 states with the highest number of policies sold.*
- *Finally, you will create a new DataFrame that contains the number of policies sold by month for each of the top 3 states.*

In [46]:
#Policies (customer) - state/month - Top 3
state_month = (
    df.groupby(["state","month"])["customer"]
    .count()
    .reset_index(name="num_policies")
)

state_month

        state  month  num_policies
0     Arizona      1          1008
1     Arizona      2           929
2  California      1          1918
3  California      2          1634
4      Nevada      1           551
5      Nevada      2           442
6      Oregon      1          1565
7      Oregon      2          1344
8  Washington      1           463
9  Washington      2           425

In [47]:
policies_sold = (
    state_month.groupby("state")["num_policies"]
    .sum()
    .reset_index()
)

policies_sold

        state  num_policies
0     Arizona          1937
1  California          3552
2      Nevada           993
3      Oregon          2909
4  Washington           888

In [48]:
policies_top = policies_sold.sort_values(
    by="num_policies",
    ascending=False
).head(3)
policies_top

        state  num_policies
1  California          3552
3      Oregon          2909
0     Arizona          1937

In [50]:
top_policies_pivot = (
    state_month
    .pivot(index= "state", columns="month",values="num_policies")
    .loc[policies_top["state"]]
)
top_policies_pivot

month          1     2
state
California  1918  1634
Oregon      1565  1344
Arizona     1008   929

7. The marketing team wants to analyze the effect of different marketing channels on the customer response rate.

Hint: You can use melt to unpivot the data and create a table that shows the customer response rate (those who responded "Yes") by marketing channel.

External Resources for Data Filtering: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

In [51]:
#marketing channels/customer_response_rate
df["sales_channel"].unique()

array(['Agent', 'Call Center', 'Branch', 'Web'], dtype=object)

In [52]:
df_channels = pd.get_dummies(df,columns=["sales_channel"]) 
df_channels

,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,income,...,renew_offer_type,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month,sales_channel_Agent,sales_channel_Branch,sales_channel_Call Center,sales_channel_Web
0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,48029,...,Offer3,292.800000,Four-Door Car,Medsize,NaN,2,True,False,False,False
1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,0,...,Offer4,744.924331,Four-Door Car,Medsize,NaN,1,False,False,True,False
2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,22139,...,Offer3,480.000000,SUV,Medsize,A,2,False,False,True,False
3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,49078,...,Offer2,484.013411,Four-Door Car,Medsize,A,1,False,True,False,False
4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,23675,...,Offer1,707.925645,Four-Door Car,Medsize,NaN,1,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10905,FE99816,Nevada,15563.369440,No,Premium,Bachelor,2011-01-19,Unemployed,F,0,...,Offer3,1214.400000,Luxury Car,Medsize,A,1,False,False,False,True
10906,KX53892,Oregon,5259.444853,No,Basic,College,2011-01-06,Employed,F,61146,...,Offer2,273.018929,Four-Door Car,Medsize,A,1,False,True,False,False
10907,TL39050,Arizona,23893.304100,No,Extended,Bachelor,2011-02-06,Employed,F,39837,...,Offer1,381.306996,Luxury SUV,Medsize,NaN,2,False,False,False,True
10908,WA60547,California,11971.977650,No,Premium,College,2011-02-13,Employed,F,64195,...,Offer1,618.288849,SUV,Medsize,A,2,False,True,False,False
10909,IV32877,NaN,6857.519928,NaN,Basic,Bachelor,2011-01-08,Unemployed,M,0,...,Offer4,1021.719397,SUV,Medsize,NaN,1,False,False,False,True

In [54]:
melted = df_channels.melt(
    id_vars = ["response"],
    #Seleccionar las que tienen sales_channel que son las que quiero convertir a filas
    value_vars = [col for col in df_channels.columns if "sales_channel" in col],
    var_name="channel", #nombre a la columna de los nuevos valores
    value_name="is_channel" #nombre a la columna de los nuevos valores de su lista
)

melted #Convierte algo ancho (columnas) en algo largo (filas)

      response              channel  is_channel
0           No  sales_channel_Agent        True
1           No  sales_channel_Agent       False
2           No  sales_channel_Agent       False
3          Yes  sales_channel_Agent       False
4           No  sales_channel_Agent       False
...        ...                  ...         ...
43635       No    sales_channel_Web        True
43636       No    sales_channel_Web       False
43637       No    sales_channel_Web        True
43638       No    sales_channel_Web       False
43639      NaN    sales_channel_Web        True

[43640 rows x 3 columns]

In [55]:
melted = melted[melted["is_channel"]== 1]
melted #Filtrar solo las que tienen el canal (True o 1)

      response              channel  is_channel
0           No  sales_channel_Agent        True
5          NaN  sales_channel_Agent        True
9           No  sales_channel_Agent        True
12          No  sales_channel_Agent        True
14          No  sales_channel_Agent        True
...        ...                  ...         ...
43621       No    sales_channel_Web        True
43629       No    sales_channel_Web        True
43635       No    sales_channel_Web        True
43637       No    sales_channel_Web        True
43639      NaN    sales_channel_Web        True

[10910 rows x 3 columns]

In [56]:
response_rate = (
    melted.groupby("channel")["response"]
    .apply(lambda x:(x=="Yes").mean())
    .reset_index(name="response_rate")
)

response_rate #% of customers that answered Yes

                     channel  response_rate
0        sales_channel_Agent       0.180053
1       sales_channel_Branch       0.107876
2  sales_channel_Call Center       0.103223
3          sales_channel_Web       0.108856